version: '3.3'

services:
    deliverymuch-challenge:
        image: 'golang:1.15.2-alpine3.12'
        working_dir: /go/src/github.com/deliverymuch-challenge
        ports:
            - 8080:8080
        volumes:
            - './:/go/src/github.com/deliverymuch-challenge'
        environment:
            GIPHY_API_TOKEN: "LyKGPGg76vk1mQ0jJM7mevHym3KM6NVC"
            GIPHY_URL: "http://api.giphy.com/v1/gifs/search"
            PUPPY_URL: "http://www.recipepuppy.com/api/"
        entrypoint:
            - go
            - run
            - -mod=vendor
            - ./cmd/api